import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { Buffer } from 'node:buffer';
import { fileURLToPath, URL } from 'node:url';
import { restoreHistoricalOutput } from '../../scripts/restore-historical-output.mjs';

const originalPng = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLttAAAAABJRU5ErkJggg==', 'base64');
const generatedPng = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64');
const pngOriginalSha = 'd8aeb7b31114535bbf9035568464d5eb3dadfabaa70525a487d2c04571203426';
const pngGeneratedSha = '431ced6916a2a21a156e38701afe55bbd7f88969fbbfc56d7fe099d47f265460';
const hash = (file) => createHash('sha256').update(fs.readFileSync(file)).digest('hex');
// Fixtures are deliberately retained in the OS temporary directory for inspection.
function fixture(json = false, name = 'historical.png') {
  const root = fs.mkdtempSync(path.join(tmpdir(), 'blackjack-h1-'));
  const directory = path.join(root, "Windows paths 空格 ' [fixture]");
  fs.mkdirSync(directory);
  const original = json ? Buffer.from('{"original":true}\r\n') : originalPng;
  const generated = json ? Buffer.from('{"generated":true}\n') : generatedPng;
  const options = {
    targetPath: path.join(directory, name), backupPath: path.join(root, 'backup.bin'),
    archivePath: path.join(root, 'archive', 'generated.bin'), diagnosticPath: path.join(root, 'failure.json'),
    expectedOriginalSha256: json ? 'b394f0692c06177a3960586e9ffa8f5ba3888a720acdaf62e6461398935bc992' : pngOriginalSha,
    expectedGeneratedSha256: json ? 'b0ec07581d579e53bbad320af611ba477d29110c5238a8f4396a5e9c7382c99d' : pngGeneratedSha,
  };
  fs.writeFileSync(options.backupPath, original, { flag: 'wx' });
  fs.writeFileSync(options.targetPath, generated, { flag: 'wx' });
  return { root, options, original, generated };
}
function failure(f, overrides, message) {
  let thrown;
  assert.throws(() => { try { restoreHistoricalOutput(f.options, { ...fs, ...overrides }); } catch (error) { thrown = error; throw error; } }, message);
  assert.equal(thrown.restorationFailure.status, 'FAIL');
  assert.equal(hash(f.options.backupPath), f.options.expectedOriginalSha256);
  assert.equal(JSON.parse(fs.readFileSync(f.options.diagnosticPath, 'utf8')).status, 'FAIL');
  return thrown.restorationFailure;
}

for (const json of [false, true]) test(`normal ${json ? 'JSON' : 'PNG'} restores exact bytes, archives generated bytes, cleans temporary files`, () => {
  const f = fixture(json, json ? 'historical.json' : 'historical.png');
  const record = restoreHistoricalOutput(f.options);
  assert.equal(record.status, 'PASS'); assert.equal(record.replacementAttempts, 1);
  assert.deepEqual(fs.readFileSync(f.options.targetPath), f.original);
  assert.deepEqual(fs.readFileSync(f.options.archivePath), f.generated);
  assert.deepEqual(fs.readFileSync(f.options.backupPath), f.original);
  assert.equal(hash(f.options.targetPath), f.options.expectedOriginalSha256);
  assert.equal(hash(f.options.archivePath), f.options.expectedGeneratedSha256);
  assert.equal(fs.existsSync(record.temporaryPath), false);
  assert.equal(fs.existsSync(record.replacementPath), false);
  assert.equal(fs.existsSync(f.options.diagnosticPath), false);
});
test('archive is verified before target replacement and target is never directly written', () => {
  const f = fixture(); let calls = 0;
  restoreHistoricalOutput(f.options, { ...fs,
    writeFileSync(file, bytes, options) { assert.notEqual(file, f.options.targetPath); return fs.writeFileSync(file, bytes, options); },
    renameSync(from, to) {
      calls++;
      assert.equal(hash(f.options.archivePath), pngGeneratedSha);
      assert.equal(hash(f.options.targetPath), pngGeneratedSha);
      assert.equal(hash(from), pngOriginalSha);
      assert.equal(path.dirname(from), path.dirname(to));
      fs.renameSync(from, to);
    },
  });
  assert.equal(calls, 1);
});
test('original backup hash mismatch fails before archiving or replacing', () => {
  const f = fixture(); f.options.expectedOriginalSha256 = '0'.repeat(64);
  assert.throws(() => restoreHistoricalOutput(f.options), /Original backup SHA256 mismatch/);
  assert.equal(hash(f.options.targetPath), pngGeneratedSha);
  assert.equal(hash(f.options.backupPath), pngOriginalSha);
  assert.equal(fs.existsSync(f.options.archivePath), false);
});
test('generated target hash mismatch fails before mutation', () => {
  const f = fixture(); f.options.expectedGeneratedSha256 = '0'.repeat(64);
  assert.throws(() => restoreHistoricalOutput(f.options), /Generated target SHA256 mismatch/);
  assert.equal(hash(f.options.targetPath), pngGeneratedSha);
  assert.equal(fs.existsSync(f.options.archivePath), false);
});
test('archive verification mismatch fails before any replacement', () => {
  const f = fixture(); let replacements = 0;
  failure(f, {
    readFileSync(file, ...args) { return file === f.options.archivePath ? Buffer.from('injected corrupt archive read') : fs.readFileSync(file, ...args); },
    renameSync() { replacements++; },
  }, /Generated archive SHA256 mismatch/);
  assert.equal(replacements, 0); assert.equal(hash(f.options.targetPath), pngGeneratedSha);
  assert.equal(hash(f.options.archivePath), pngGeneratedSha);
});
test('existing archive is never overwritten', () => {
  const f = fixture(); fs.mkdirSync(path.dirname(f.options.archivePath)); fs.writeFileSync(f.options.archivePath, 'prior archive');
  failure(f, {}, /EEXIST/);
  assert.equal(fs.readFileSync(f.options.archivePath, 'utf8'), 'prior archive');
  assert.equal(hash(f.options.targetPath), pngGeneratedSha);
});
test('temporary write failure preserves target, archive, backup and partial fixture evidence', () => {
  const f = fixture();
  const record = failure(f, {
    writeFileSync(file, bytes, options) {
      if (path.basename(file).startsWith('.h1-original-')) { fs.writeFileSync(file, 'partial fixture'); throw new Error('injected temporary write failure'); }
      return fs.writeFileSync(file, bytes, options);
    },
  }, /injected temporary write failure/);
  assert.equal(hash(f.options.targetPath), pngGeneratedSha); assert.equal(hash(f.options.archivePath), pngGeneratedSha);
  assert.equal(fs.readFileSync(record.temporaryPath, 'utf8'), 'partial fixture');
});
test('temporary hash mismatch fails before replacement and preserves the original copy', () => {
  const f = fixture();
  const record = failure(f, {
    readFileSync(file, ...args) { return path.basename(file).startsWith('.h1-original-') ? Buffer.from('injected read mismatch') : fs.readFileSync(file, ...args); },
  }, /Temporary original SHA256 mismatch/);
  assert.equal(hash(record.temporaryPath), pngOriginalSha); assert.equal(hash(f.options.targetPath), pngGeneratedSha);
});
test('replacement write failure retains verified temporary original', () => {
  const f = fixture();
  const record = failure(f, {
    writeFileSync(file, bytes, options) { if (path.basename(file).startsWith('.h1-replace-')) throw new Error('injected replacement write failure'); return fs.writeFileSync(file, bytes, options); },
  }, /injected replacement write failure/);
  assert.equal(hash(record.temporaryPath), pngOriginalSha); assert.equal(hash(f.options.targetPath), pngGeneratedSha);
});
test('replacement hash mismatch fails before rename and retains both copies', () => {
  const f = fixture();
  const record = failure(f, {
    readFileSync(file, ...args) { return path.basename(file).startsWith('.h1-replace-') ? Buffer.from('injected read mismatch') : fs.readFileSync(file, ...args); },
  }, /Replacement SHA256 mismatch/);
  assert.equal(hash(record.temporaryPath), pngOriginalSha); assert.equal(hash(record.replacementPath), pngOriginalSha);
  assert.equal(hash(f.options.targetPath), pngGeneratedSha);
});
test('rename failure is fail-closed, attempts exactly once, emits full error telemetry', () => {
  const f = fixture(); let attempts = 0;
  const record = failure(f, {
    renameSync() { attempts++; throw Object.assign(new Error('controlled UNKNOWN fixture'), { errno: -4094, code: 'UNKNOWN', syscall: 'rename' }); },
  }, /controlled UNKNOWN fixture/);
  assert.equal(attempts, 1); assert.equal(record.operation, 'replace target once');
  assert.equal(record.errno, -4094); assert.equal(record.code, 'UNKNOWN'); assert.equal(record.syscall, 'rename');
  assert.equal(record.nodeVersion, process.version); assert.equal(record.processId, process.pid);
  assert.equal(record.targetExists, true); assert.equal(record.targetMetadata.size, generatedPng.length);
  assert.equal(record.backupSha256, pngOriginalSha); assert.equal(record.currentTargetSha256, pngGeneratedSha);
  assert.equal(record.parentDirectory, path.dirname(f.options.targetPath));
  assert.equal(record.sourcePath, record.replacementPath); assert.equal(record.targetPath, f.options.targetPath);
  assert.ok(record.stack.includes('controlled UNKNOWN fixture')); assert.ok(Number.isFinite(Date.parse(record.at)));
  if (process.platform === 'win32') { assert.equal(record.windows.status, 'PASS'); assert.equal(typeof record.windows.attributes, 'number'); }
  assert.equal(hash(f.options.targetPath), pngGeneratedSha); assert.equal(hash(f.options.archivePath), pngGeneratedSha);
  assert.equal(hash(record.temporaryPath), pngOriginalSha); assert.equal(hash(record.replacementPath), pngOriginalSha);
});
test('post-replacement hash mismatch fails and preserves verified temporary original', () => {
  const f = fixture(); let replaced = false;
  const record = failure(f, {
    renameSync(from, to) { fs.renameSync(from, to); replaced = true; },
    readFileSync(file, ...args) { return replaced && file === f.options.targetPath ? Buffer.from('injected post-rename read mismatch') : fs.readFileSync(file, ...args); },
  }, /Restored target SHA256 mismatch/);
  assert.equal(record.operation, 'verify restored target'); assert.equal(hash(record.temporaryPath), pngOriginalSha);
  assert.equal(hash(f.options.backupPath), pngOriginalSha); assert.equal(hash(f.options.archivePath), pngGeneratedSha);
});
test('cleanup failure returns failure and retains verified temporary original', () => {
  const f = fixture();
  const record = failure(f, { unlinkSync() { throw new Error('injected cleanup failure'); } }, /injected cleanup failure/);
  assert.equal(hash(record.temporaryPath), pngOriginalSha); assert.equal(hash(f.options.targetPath), pngOriginalSha);
});
test('read-only Windows diagnostic probe reports its own HRESULT without claiming Node root cause', () => {
  const f = fixture(); fs.unlinkSync(f.options.targetPath);
  assert.throws(() => restoreHistoricalOutput(f.options), /ENOENT/);
  const record = JSON.parse(fs.readFileSync(f.options.diagnosticPath, 'utf8'));
  assert.equal(record.targetExists, false);
  if (process.platform === 'win32') { assert.equal(record.windows.status, 'FAIL'); assert.match(record.windows.nativeError.hresultHex, /^0x[0-9A-F]{8}$/); }
  assert.match(record.nativeErrorFromFailedOperation, /NOT AVAILABLE/);
});
test('Windows separators, Unicode, spaces, apostrophes and brackets are handled as literal paths', () => {
  const f = fixture(false, "restored ' [七].png");
  restoreHistoricalOutput(f.options);
  assert.equal(hash(f.options.targetPath), pngOriginalSha);
});
test('diagnostic write failure never masks original error or destroys existing evidence', () => {
  const f = fixture(); fs.writeFileSync(f.options.diagnosticPath, 'prior diagnostic');
  let thrown;
  assert.throws(() => { try { restoreHistoricalOutput(f.options, { ...fs, renameSync() { throw new Error('original failure'); } }); } catch (error) { thrown = error; throw error; } }, /original failure/);
  assert.equal(thrown.restorationFailure.diagnosticWriteError.code, 'EEXIST');
  assert.equal(fs.readFileSync(f.options.diagnosticPath, 'utf8'), 'prior diagnostic'); assert.equal(hash(f.options.targetPath), pngGeneratedSha);
});
test('CLI returns non-zero for a hash failure and preserves historical fixture bytes', () => {
  const f = fixture(); f.options.expectedOriginalSha256 = '0'.repeat(64);
  const plan = path.join(f.root, 'plan.json'); fs.writeFileSync(plan, JSON.stringify(f.options));
  const run = spawnSync(process.execPath, [fileURLToPath(new URL('../../scripts/restore-historical-output.mjs', import.meta.url)), plan], { encoding: 'utf8' });
  assert.equal(run.status, 1); assert.match(run.stderr, /Original backup SHA256 mismatch/);
  assert.equal(hash(f.options.targetPath), pngGeneratedSha); assert.equal(hash(f.options.backupPath), pngOriginalSha);
});
